from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from io import BytesIO

class PDFGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.buffer = BytesIO()
        
    def _get_header_style(self):
        return ParagraphStyle(
            'Header',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=colors.darkblue,
            spaceAfter=12
        )

    def generate_roadmap_pdf(self, topic, duration, roadmap_data):
        doc = SimpleDocTemplate(self.buffer, pagesize=LETTER)
        elements = []
        
        # Title
        elements.append(Paragraph(f"Learning Roadmap: {topic}", self._get_header_style()))
        elements.append(Paragraph(f"Duration: {duration} | Generated by Student GenAI", self.styles['Normal']))
        elements.append(Spacer(1, 20))
        
        # Weeks
        for week in roadmap_data.get('roadmap', []):
            # Week Header
            elements.append(Paragraph(f"Week {week['week']}: {week['title']}", self.styles['Heading2']))
            elements.append(Paragraph(f"<b>Focus:</b> {week['description']}", self.styles['Normal']))
            elements.append(Spacer(1, 10))
            
            # Topics
            elements.append(Paragraph("<b>Key Topics:</b>", self.styles['Normal']))
            for t in week['topics']:
                elements.append(Paragraph(f"• {t}", self.styles['Bullet']))
            
            elements.append(Spacer(1, 10))
            
            # Project
            elements.append(Paragraph(f"<b>Mini-Project:</b> {week['project']}", self.styles['BodyText']))
            elements.append(Paragraph("_" * 60, self.styles['Normal'])) # Separator
            elements.append(Spacer(1, 20))
            
        doc.build(elements)
        self.buffer.seek(0)
        return self.buffer

    def generate_chapter_pdf(self, topic, content):
        doc = SimpleDocTemplate(self.buffer, pagesize=LETTER)
        elements = []
        
        elements.append(Paragraph(f"Study Chapter: {topic}", self._get_header_style()))
        elements.append(Spacer(1, 20))
        
        # ReportLab doesn't parse Markdown directly, so we do a simple split
        # For production, you'd use a markdown-to-pdf parser, but this works for text
        lines = content.split('\n')
        for line in lines:
            if line.startswith('#'):
                style = self.styles['Heading2']
                text = line.replace('#', '').strip()
            elif line.startswith('-') or line.startswith('*'):
                style = self.styles['Bullet']
                text = line[1:].strip()
            else:
                style = self.styles['Normal']
                text = line
            
            if text.strip():
                elements.append(Paragraph(text, style))
                elements.append(Spacer(1, 6))
                
        doc.build(elements)
        self.buffer.seek(0)
        return self.buffer

    def generate_debug_report(self, code, error, solution):
        doc = SimpleDocTemplate(self.buffer, pagesize=LETTER)
        elements = []
        
        elements.append(Paragraph("AI Debug Report", self._get_header_style()))
        elements.append(Spacer(1, 20))
        
        # Code Section
        elements.append(Paragraph("<b>Broken Code:</b>", self.styles['Heading3']))
        code_style = ParagraphStyle('Code', parent=self.styles['Code'], backColor=colors.lightgrey)
        elements.append(Paragraph(code, code_style))
        elements.append(Spacer(1, 10))
        
        # Error Section
        elements.append(Paragraph("<b>Error Message:</b>", self.styles['Heading3']))
        elements.append(Paragraph(error, self.styles['Normal']))
        elements.append(Spacer(1, 10))
        
        # Solution Section
        elements.append(Paragraph("<b>AI Solution:</b>", self.styles['Heading3']))
        elements.append(Paragraph(solution, self.styles['BodyText']))
        
        doc.build(elements)
        self.buffer.seek(0)
        return self.buffer

    def generate_assessment_pdf(self, title, questions, results=None):
        doc = SimpleDocTemplate(self.buffer, pagesize=LETTER)
        elements = []
        
        elements.append(Paragraph(f"Assessment: {title}", self._get_header_style()))
        
        if results:
            elements.append(Paragraph(f"<b>Final Score: {results['score']}/{results['total']}</b>", self.styles['Heading2']))
            
        elements.append(Spacer(1, 20))
        
        for i, q in enumerate(questions):
            elements.append(Paragraph(f"Q{i+1}: {q.get('q')}", self.styles['Heading3']))
            
            # Options
            if 'options' in q:
                for opt in q['options']:
                    elements.append(Paragraph(f"• {opt}", self.styles['Normal']))
            
            # Correct Answer (if generating results/key)
            if results or 'answer' in q:
                ans = q.get('answer')
                elements.append(Spacer(1, 5))
                elements.append(Paragraph(f"<b>Correct Answer:</b> {ans}", self.styles['BodyText']))
                
            elements.append(Spacer(1, 15))
            
        doc.build(elements)
        self.buffer.seek(0)
        return self.buffer
