import streamlit as st
import shutil
import os
from frontend.utils.helpers import get_projects, read_project_file

# Helper to ensure we get the absolute path
# NOTE: In a real production app, this should be an API call to the backend.
# For this local setup, we access the shared folder directly.
PROJECTS_DIR = os.path.join(os.getcwd(), "generated_projects")

# --- CALLBACKS ---
def cb_go_to_github(project_name):
    st.session_state['social_active_tab'] = "github"
    st.session_state['prefill_gh_project'] = project_name
    st.session_state['navigate_to'] = "Career & Social"

def cb_go_to_linkedin(project_name):
    st.session_state['social_active_tab'] = "linkedin"
    st.session_state['prefill_li_topic'] = project_name
    st.session_state['prefill_li_desc'] = f"I just built {project_name} using AI! It's a full-stack application generated in minutes."
    st.session_state['navigate_to'] = "Career & Social"

def cb_delete_project(full_path):
    try:
        if os.path.exists(full_path):
            shutil.rmtree(full_path)
            st.session_state['show_toast'] = "✅ Project deleted successfully!"
        else:
            st.session_state['show_error'] = f"Folder not found at: {full_path}"
    except Exception as e:
        st.session_state['show_error'] = f"Could not delete: {e}"

# --- MAIN RENDERER ---
def render_projects_page():
    # --- HEADER STYLE ---
    st.markdown("""
    <style>
        h1 {
            background: linear-gradient(90deg, #00C9FF 0%, #92FE9D 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            font-weight: 800;
        }
        /* Custom file list styling */
        div[role="radiogroup"] label {
            background-color: rgba(255,255,255,0.05);
            border: 1px solid rgba(255,255,255,0.1);
            padding: 10px;
            border-radius: 8px;
            margin-bottom: 5px;
            transition: all 0.2s;
        }
        div[role="radiogroup"] label:hover {
            background-color: rgba(255,255,255,0.1);
            border-color: #92FE9D;
        }
    </style>
    """, unsafe_allow_html=True)

    st.title("📂 Project Explorer")
    
    user = st.session_state.get('user')
    if not user:
        st.error("Please login to view projects.")
        return

    # Handle Callback Messages
    if 'show_toast' in st.session_state:
        st.toast(st.session_state['show_toast'], icon="🗑️")
        del st.session_state['show_toast']
    if 'show_error' in st.session_state:
        st.error(st.session_state['show_error'])
        del st.session_state['show_error']

    # --- TOP ACTIONS ---
    col_top1, col_top2 = st.columns([3, 1])
    with col_top1:
         st.markdown("Browse and manage the applications generated by your AI agents.")
    with col_top2:
        if st.button("🔄 Refresh List", use_container_width=True):
            st.rerun()

    # --- LOAD PROJECTS ---
    projects = get_projects(PROJECTS_DIR, user['id'])
    
    if not projects:
        st.info("No projects found. Go to **Builder** to create one!")
        return

    # --- PROJECT SELECTION ---
    with st.container(border=True):
        project_names = list(projects.keys())
        selected_project = st.selectbox("Select Active Project", project_names, key="project_select_box")

    if selected_project:
        st.markdown("<br>", unsafe_allow_html=True)
        
        # --- ACTION BAR ---
        c1, c2, c3 = st.columns(3)
        with c1:
            st.button("🐙 Push to GitHub", use_container_width=True, key="btn_gh", 
                     on_click=cb_go_to_github, args=(selected_project,))
        with c2:
            st.button("✍️ LinkedIn Post", use_container_width=True, key="btn_li", 
                     on_click=cb_go_to_linkedin, args=(selected_project,))
        with c3:
            full_path = os.path.join(PROJECTS_DIR, f"user_{user['id']}", selected_project)
            st.button("🗑️ Delete Project", type="primary", use_container_width=True, key="btn_del", 
                     on_click=cb_delete_project, args=(full_path,))

        st.markdown("---")
        
        # --- FILE EXPLORER LAYOUT ---
        files = projects[selected_project]
        
        col_list, col_view = st.columns([1, 2.5])
        
        # Left: File List
        with col_list:
            st.subheader("Files")
            with st.container(height=500, border=True):
                selected_file = st.radio("Select File", files, label_visibility="collapsed", key="project_file_radio")
        
        # Right: Code Viewer
        with col_view:
            st.subheader("Code Editor View")
            if selected_file:
                with st.container(height=500, border=True):
                    st.caption(f"Editing: {selected_file}")
                    content = read_project_file(PROJECTS_DIR, user['id'], selected_project, selected_file)
                    
                    ext = selected_file.split('.')[-1].lower()
                    lang_map = {"py": "python", "js": "javascript", "html": "html", "css": "css", "json": "json", "md": "markdown", "sql": "sql"}
                    lang = lang_map.get(ext, "text")
                    
                    st.code(content, language=lang, line_numbers=True)
            else:
                st.info("Select a file to view code.")
